Updated to run 2017 MC/DATA
cbeiraod/cmgtools-lite pull request #1
Opened 2018-04-26 17:15 UTC by diogodebastos

2018-04-26 17:40 UTC, cbeiraod requested changes

2018-04-26 17:40 UTC, cbeiraod commented on TTHAnalysis/cfg/run_susyStop4Body_cfg.py
> +isoTrackAna.useLegacy2016 = True
Isto devia estar num if...
Se estiveres a analisar os dados de 2017(18) não queres usar a versão legacy.

2018-04-26 17:40 UTC, cbeiraod commented on TTHAnalysis/python/analyzers/ntupleTypes.py
> +from PhysicsTools.Heppy.analyzers.core.autovars import NTupleObjectType
You shouldn't do any changes on this file... Remember that we want to make changes only to the Stop4Body specific parts.  Revert all changes on this file. It is mostly from spaces that your editor automatically removed from the end of lines.

2018-04-27 16:14 UTC, cbeiraod requested changes

2018-04-27 16:14 UTC, cbeiraod commented on TTHAnalysis/python/analyzers/ntupleTypes.py
> +    NTupleVariable("jetNDauNotPV",    lambda lepton : sum(x.charge()!=0 and x.fromPV()<=2 for x in lepton.jet.daughterPtrVector()) if hasattr(lepton,'jet') and lepton.jet != lepton else -1, help="n c
What changed here?

2018-04-27 16:14 UTC, cbeiraod commented on TTHAnalysis/python/analyzers/ntupleTypes.py
> +    # ---------------
You forgot to undo your changes here

2018-04-27 16:14 UTC, cbeiraod commented on TTHAnalysis/python/analyzers/ntupleTypes.py
> +
And you forgot to undo your changes here too

2018-04-30 22:08 UTC, diogodebastos commented on TTHAnalysis/python/analyzers/ntupleTypes.py
> +    NTupleVariable("jetNDauNotPV",    lambda lepton : sum(x.charge()!=0 and x.fromPV()<=2 for x in lepton.jet.daughterPtrVector()) if hasattr(lepton,'jet') and lepton.jet != lepton else -1, help="n c
I just added whitespaces to match the 94X_dev branch version. But I did it in the wrong place, so I'll fixe it.

2018-04-30 22:12 UTC, diogodebastos commented on TTHAnalysis/python/analyzers/ntupleTypes.py
> +    # ---------------
:+1:

2018-04-30 22:13 UTC, diogodebastos commented on TTHAnalysis/python/analyzers/ntupleTypes.py
> +
:+1:

2018-05-01 10:57 UTC, merged